- type: technology
  id: LuaBluespaceArt
  name: lua-research-technology-bluespace-art
  entityIcon: SprayPainterMagic
  discipline: NFService
  factions:
  - Nanotrasen
  - Syndicate
  tier: 3
  cost: 20000
  recipeUnlocks:
  - SprayPainterMagic
  - CrayonMagic
  prerequisiteLineType: Diagonal
  technologyPrerequisites:
  - NFAdvancedEntertainment
  position: -7.565, -3.331
...
